exports.PAY_TYPE = {
  CREDIT_CARD: 'CREDIT_CARD',
  BANK_BOOK: 'BANK_BOOK',
  MY_PAY: 'MY_PAY',
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
};

exports.TALK_TEMPLATE_TYPE = {
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
  ACCOUNT_LINK: 'ACCOUNT_LINK',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
};

exports.POST_STATUS = {
  PENDING: 'PENDING',
  ACCEPT: 'ACCEPT',
  REJECT: 'REJECT',
  CANCEL: 'CANCEL',
  START: 'START',
};

exports.MATCH_STATUS = {
  PROGRESS: 'PROGRESS',
  DELIVER_CANCEL: 'DELIVER_CANCEL',
  DELIVER_DONE: 'DELIVER_DONE',
  RECEIVER_DONE: 'RECEIVER_DONE',
  DONE: 'DONE',
};
