module.exports = [
    {
        countryCode: "AUS",
        warehouse: "Main",
        market: "AU",
        country: "AU",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "AUS",
        warehouse: "Main",
        market: "AU",
        country: "AU",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "HKG",
        warehouse: "Main",
        market: "HK",
        country: "HK",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "IDN",
        warehouse: "Main",
        market: "ID",
        country: "ID",
        shippingMethodType: "Economy",
        shippingMethodLocation: null,
    },
    {
        countryCode: "IDN",
        warehouse: "Surabaya",
        market: "ID",
        country: "ID",
        shippingMethodType: "Economy",
        shippingMethodLocation: "Surabaya",
    },
    {
        countryCode: "JPN",
        warehouse: "Main",
        market: "JP",
        country: "JP",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "MYS",
        warehouse: "Main",
        market: "MY",
        country: "MY",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "NZL",
        warehouse: "Main",
        market: "NZ",
        country: "NZ",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "NZL",
        warehouse: "Main",
        market: "NZ",
        country: "NZ",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "PHL",
        warehouse: "Main",
        market: "PH",
        country: "PH",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "SGP",
        warehouse: "Main",
        market: "SG",
        country: "SG",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "THA",
        warehouse: "Main",
        market: "TH",
        country: "TH",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "TWN",
        warehouse: "Main",
        market: "TW",
        country: "TW",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "VNM",
        warehouse: "Main",
        market: "VN",
        country: "VN",
        shippingMethodType: null,
        shippingMethodLocation: null,
    },
    {
        countryCode: "XHK",
        warehouse: "Main",
        market: "SG",
        country: "HK",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XHK",
        warehouse: "Main",
        market: "SG",
        country: "HK",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "XID",
        warehouse: "Main",
        market: "SG",
        country: "ID",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XID",
        warehouse: "Main",
        market: "SG",
        country: "ID",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "XJP",
        warehouse: "Main",
        market: "SG",
        country: "JP",
        shippingMethodType: "Economy",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XJP",
        warehouse: "Main",
        market: "SG",
        country: "JP",
        shippingMethodType: "Economy",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "XKR",
        warehouse: "Main",
        market: "SG",
        country: "KR",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XMY",
        warehouse: "Main",
        market: "SG",
        country: "MY",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XMY",
        warehouse: "Main",
        market: "SG",
        country: "MY",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "XNZ",
        warehouse: "Main",
        market: "NZ",
        country: "NZ",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XNZ",
        warehouse: "Main",
        market: "NZ",
        country: "NZ",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
    {
        countryCode: "XPH",
        warehouse: "Main",
        market: "SG",
        country: "PH",
        shippingMethodType: "Expedited",
        shippingMethodLocation: null,
    },
    {
        countryCode: "XPH",
        warehouse: "Main",
        market: "SG",
        country: "PH",
        shippingMethodType: "Expedited",
        shippingMethodLocation: "Singapore, Yamato Warehouse",
    },
]