service: unishop-dictionary-api

plugins:
  - serverless-domain-manager
  - serverless-api-compression

custom:
  verifyTokenArns:
    dev: arn:aws:lambda:ap-northeast-2:153874506602:function:unishop-authorization-dev-verifyToken
    prod: arn:aws:lambda:ap-northeast-2:153874506602:function:unishop-authorization-prod-verifyToken
  useVerifyTokenArn: ${self:custom.verifyTokenArns.${self:provider.stage}}
  domains:
    dev: member-calls2-kr-dev.unicity.com
    prod: member-calls2-kr.unicity.com
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${self:provider.stage}
    basePath: ${self:provider.environment.MODULE_KEY}
  dbConfigs:
    dev:
      host: "calls-kr.cluster-cs23rdjjrds4.ap-northeast-2.rds.amazonaws.com"
      dbName: "calls-kr-dev"
      user: "lambdaKrDev"
      password: "FzTPpDeezTtFW2gS"
    prod:
      host: "calls-kr.cluster-cs23rdjjrds4.ap-northeast-2.rds.amazonaws.com"
      dbName: "calls-kr"
      user: "lambdaKr"
      password: "rdStaC9s9rQ2HeHl"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  endpointType: regional
  apiName: unishop_${self:provider.environment.MODULE_KEY}_${self:provider.stage}
  deploymentBucket: ushop-serverless-applications-kor
  apiGateway:
    minimumCompressionSize: 10000
  environment:
    MODULE_KEY: dictionary
    DB_HOST: ${self:custom.dbConfigs.${self:provider.stage}.host}
    DB_DBNAME: ${self:custom.dbConfigs.${self:provider.stage}.dbName}
    DB_USER: ${self:custom.dbConfigs.${self:provider.stage}.user}
    DB_PASSWORD: ${self:custom.dbConfigs.${self:provider.stage}.password}
    S3_BUCKET_TEMP: temp.ushop.unicity.com
    FILE_EXPIRE_MINUTES: 10
  vpc:
    securityGroupIds:
      - sg-0eae031a176831694
    subnetIds:
      - subnet-0204937de4af72758
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "arn:aws:s3:::*"

functions:
  getDictionaryList:
    handler: src/functions/getDictionaryList.handler
    events:
      - http:
          path: /data
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.useVerifyTokenArn}
            resultTtlInSeconds: 0
    timeout: 30
  addDictionary:
    handler: src/functions/addDictionary.handler
    events:
      - http:
          path: /data
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.useVerifyTokenArn}
            resultTtlInSeconds: 0
  deleteDictionary:
    handler: src/functions/deleteDictionary.handler
    events:
      - http:
          path: /data/{id}
          method: delete
          cors: true
          authorizer:
            arn: ${self:custom.useVerifyTokenArn}
            resultTtlInSeconds: 0
  getListOfLanguages:
    handler: src/functions/getListOfLanguages.handler
    events:
      - http:
          path: /list/languages
          method: get
          cors: true
  editDictionaryMultiple:
    handler: src/functions/editDictionaryMultiple.handler
    events:
      - http:
          path: /editDictionaryMultiple/{countryCode}
          method: patch
          cors: true
          authorizer:
            arn: ${self:custom.useVerifyTokenArn}
            resultTtlInSeconds: 0
  getPublishDictionary:
    handler: src/functions/getPublishDictionary.handler
    events:
      - http:
          path: /publish
          method: get
          cors: true
    timeout: 30
  googleTranslate:
    handler: src/functions/googleTranslate.handler
    events:
      - http:
          path: /translate
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.useVerifyTokenArn}
            resultTtlInSeconds: 0
  exportDictionaryList:
    handler: src/functions/exportDictionaryList.handler
    events:
      - http:
          path: /export
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.useVerifyTokenArn}
            resultTtlInSeconds: 0
  getHistoryOne:
    handler: src/functions/getHistoryOne.handler
    events:
      - http:
          path: /history/{id}
          method: get
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
