service: unishop-ordercalc

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  deploymentBucket: ushop-serverless-applications
  timeout: 29
  endpointType: regional
  apiName: ${self:service}_${self:provider.stage}
  environment:
    HYDRA_VERSION: v5a
    STAGE: ${self:provider.stage}
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParametersByPath
      Resource:
        - 'Fn::Join':
          - ':'
          - - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter/*'

functions:
  index:
    handler: src/index.main
    events:
      - http:
          path: /
          method: post
          cors: true
  test:
    handler: src/test.main
    events:
      - http:
          path: /test
          method: get
          cors: true

custom:
  domains:
    local: member-calls2-dev-kr.unicity.com
    dev: member-calls2-dev-kr.unicity.com
    prod: member-calls2-kr.unicity.com
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${self:provider.stage}
    basePath: ordercalc

plugins:
  - serverless-offline
  - serverless-domain-manager