AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'replace unishop_payment_log table in mysql

  '
Globals:
  Function:
    Timeout: 3
Resources:
  UshopPaymentLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://booktesttest/515a04833569644f85515f1a39921a85
      Handler: index.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 10
      Events:
        CreateLogApi:
          Type: Api
          Properties:
            Path: /log/create
            Method: POST
        GetPostToPaymentApi:
          Type: Api
          Properties:
            Path: /log/get/posttopayment
            Method: POST
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:BatchWriteItem
          Resource:
          - Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/unishop_payment_log
          - Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/dev_unishop_payment_log
